# -*- coding: utf-8 -*-
"""Language_trans_Mbart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLeizfrHUfmLQ_LDfXO2FSh-hEp0xKy-
"""

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

# Load the tokenizer and model
model_name = "facebook/mbart-large-50-many-to-many-mmt"
tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
model = MBartForConditionalGeneration.from_pretrained(model_name)

# Set the source and target languages (e.g., English to German)
tokenizer.src_lang = "en_XX"
text = "This is an example of language translation."

# Tokenize the input text
inputs = tokenizer(text, return_tensors="pt")

# Generate the translation, specifying the target language
translated_tokens = model.generate(**inputs, forced_bos_token_id=tokenizer.lang_code_to_id["de_DE"])
translation = tokenizer.decode(translated_tokens[0], skip_special_tokens=True)

print(f"Original: {text}")
print(f"Translation: {translation}")